# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 888703f4db196d5bf150ffc9d09b71cbdf6cf5d57c3230ea8363abf0417f7ab467cb97fed90e2824ad306ec66fb65453be73419cfb87c2688e2a5d5769711914

test:
  secret_key_base: 732a3fcb0aa767480aaa36097448b9ab894884d825f64c459591a44b5933c609f0cd3bb92e5f732a10ec589920498c844c5c9c02c95162bbfa045cd593c5a3b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
